name: Automated Review Process

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  auto-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate HTML
        if: endsWith(github.event.head_commit.modified[0], '.html')
        run: |
          npx html-validate **/*.html

      - name: Check CSS
        if: endsWith(github.event.head_commit.modified[0], '.css')
        run: |
          npx stylelint "**/*.css"

      - name: Auto Label
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Summary
        run: |
          echo "### Automated Review Summary" >> $GITHUB_STEP_SUMMARY
          echo "* Branch: ${{ github.ref }}" >> $GITHUB_STEP_SUMMARY
          echo "* Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY